---
openapi: 3.0.3
info:
  title: rails_api_base
  version: 1.0.0
servers: []
paths:
  "/api/v1/user":
    put:
      summary: update
      tags:
      - Api::V1::User
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
        example: 8vv2wcGCp6dKP1aTmc3XHg
      - name: client
        in: header
        required: true
        schema:
          type: string
        example: ZJY94qd7xs7j5W2SI9QarA
      - name: uid
        in: header
        required: true
        schema:
          type: string
        example: merle.brekke@kulas.example
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    username:
                      type: string
              required:
              - user
            example:
              user:
                email: notanemail
                username: new username
      responses:
        '400':
          description: returns the error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        items:
                          type: string
                    required:
                    - email
                required:
                - errors
              example:
                errors:
                  email:
                  - is not an email
        '422':
          description: returns the missing params error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: A required param is missing
        '200':
          description: returns success
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      uid:
                        type: string
                      provider:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - id
                    - email
                    - name
                    - username
                    - first_name
                    - last_name
                    - uid
                    - provider
                    - created_at
                    - updated_at
                required:
                - user
              example:
                user:
                  id: 26
                  email: merle.brekke@kulas.example
                  name: new username
                  username: new username
                  first_name: ''
                  last_name: ''
                  uid: merle.brekke@kulas.example
                  provider: email
                  created_at: '2023-10-19T19:06:05.713Z'
                  updated_at: '2023-10-19T19:06:05.858Z'
    get:
      summary: show
      tags:
      - Api::V1::User
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
        example: 1azB4O56vzxNnhuKbMxCnA
      - name: client
        in: header
        required: true
        schema:
          type: string
        example: 14Vc9P4RF3t5jt5s0QtwPA
      - name: uid
        in: header
        required: true
        schema:
          type: string
        example: vada_veum@rowe.example
      responses:
        '200':
          description: does not return a Set-Cookie Header
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      uid:
                        type: string
                      provider:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - id
                    - email
                    - name
                    - username
                    - first_name
                    - last_name
                    - uid
                    - provider
                    - created_at
                    - updated_at
                required:
                - user
              example:
                user:
                  id: 5
                  email: vada_veum@rowe.example
                  name: lionel
                  username: lionel
                  first_name: ''
                  last_name: ''
                  uid: vada_veum@rowe.example
                  provider: email
                  created_at: '2023-10-19T19:06:04.571Z'
                  updated_at: '2023-10-19T19:06:04.640Z'
        '404':
          description: returns status 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Couldn't find the record
  "/api/v1/users/password":
    post:
      summary: create
      tags:
      - Api::V1::Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
            example:
              email: notvalid@example.com
      responses:
        '200':
          description: does not return a Set-Cookie Header
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                - success
                - message
              example:
                success: true
                message: An email has been sent to 'kayleen@stanton.test' containing
                  instructions for resetting your password.
        '404':
          description: does not return a successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Unable to find user with email 'notvalid@example.com'.
    put:
      summary: update
      tags:
      - Api::V1::Password
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
        example: Iw7QOD_4x8I4CHgyJ3VBkg
      - name: client
        in: header
        required: true
        schema:
          type: string
        example: BfrU4lTj3vrMG28kt9swrA
      - name: uid
        in: header
        required: true
        schema:
          type: string
        example: rosendo@koss.example
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - password
              - password_confirmation
            example:
              password: '123456789'
              password_confirmation: anotherpass
      responses:
        '200':
          description: returns a successful response
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                      provider:
                        type: string
                      uid:
                        type: string
                      id:
                        type: integer
                      allow_password_change:
                        type: boolean
                      first_name:
                        type: string
                      last_name:
                        type: string
                      username:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - email
                    - provider
                    - uid
                    - id
                    - allow_password_change
                    - first_name
                    - last_name
                    - username
                    - created_at
                    - updated_at
                  message:
                    type: string
                required:
                - success
                - data
                - message
              example:
                success: true
                data:
                  email: mariel_simonis@carroll.example
                  provider: email
                  uid: mariel_simonis@carroll.example
                  id: 13
                  allow_password_change: false
                  first_name: ''
                  last_name: ''
                  username: sherman
                  created_at: '2023-10-19T19:06:05.232Z'
                  updated_at: '2023-10-19T19:06:05.469Z'
                message: Your password has been successfully updated.
        '422':
          description: does not change the password if confirmation does not match
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  errors:
                    type: object
                    properties:
                      password_confirmation:
                        type: array
                        items:
                          type: string
                      full_messages:
                        type: array
                        items:
                          type: string
                    required:
                    - password_confirmation
                    - full_messages
                required:
                - success
                - errors
              example:
                success: false
                errors:
                  password_confirmation:
                  - doesn't match Password
                  full_messages:
                  - Password confirmation doesn't match Password
  "/api/v1/users/password/edit":
    get:
      summary: edit
      tags:
      - Api::V1::Password
      parameters:
      - name: redirect_url
        in: query
        required: false
        schema:
          type: string
        example: localhost
      - name: reset_password_token
        in: query
        required: false
        schema:
          type: string
        example: njDLboMmAgEENV2qkYZ5
      responses:
        '302':
          description: returns the client id
          content:
            text/html:
              schema:
                type: string
              example: <html><body>You are being <a href="http://www.example.com://localhost?access-token=svjDMlsnj735Eb_Sv6oKRQ&amp;client=9Mict06gsQZEfLmFVp13Lg&amp;client_id=9Mict06gsQZEfLmFVp13Lg&amp;config=&amp;expiry=1760900765&amp;reset_password=true&amp;token=svjDMlsnj735Eb_Sv6oKRQ&amp;uid=darnell.mcdermott%40rutherford.example">redirected</a>.</body></html>
